<?php

namespace App\Presenters;

use Nette;
use Kdyby;
use    App\Model;
use    Tracy\Debugger;


class DromPresenter extends BasePresenter
{

	/** @var Kdyby\Doctrine\EntityManager @inject */
	public $em;


	public function startup()
	{
		parent::startup(); // TODO: Change the autogenerated stub
		$this['breadcrumbs']->add('Drom', ':Admin:Drom');
	}



	public function renderDefault()
	{
		Debugger::dump( $this->em->getRepository( Model\Entity\Category::class )->find() );

	}


	public function renderTest()
	{
		Debugger::dump( 'tralala' );

		$this['breadcrumbs']->add('test', ':Admin:Drom:test');

	}



///////component//////////////////////////////////////////////////////

	public function createComponentTestForm()
	{
		$form = new Nette\Application\UI\Form;

		$form->addText('text1', 'Text1')
			->setRequired( 'Pole text 1 je povinne.' )
			->addRule( $form::MIN_LENGTH, 'Pole text 1 musi mat dlzku najmenej %d znakov.', 6);

		$form->addText('text2', 'Text2')
			->setRequired( 'Pole text 2 je povinne.' )
			->addRule( $form::RANGE, 'Pole text 2 musi byt v rozsahu od %d do %d', [3, 6] );

		$form->addSubmit( 'sbmt', 'Submit');


		return $form;
	}



	public function editFormSubmitted( $form )
	{
		return TRUE;
	}


}
