<?php

namespace App\Presenters;

use Nette,
	App\Model,
	Tracy\Debugger;


class DromPresenter extends BasePresenter
{
	const
		TABLE_NAME = 'users',
		COLUMN_ID = 'id',
		COLUMN_NAME = 'user_name',
		COLUMN_PASSWORD = 'password',
		COLUMN_ROLE = 'role',
		COLUMN_EMAIL = 'email',
		COLUMN_ACTIVE = 'active',
		COLUMN_CONFIRMATION_CODE = 'confirmation_code';


	public function startup()
	{
		parent::startup(); // TODO: Change the autogenerated stub
		$this['breadcrumbs']->add('Drom', ':Admin:Drom');
	}



	public function renderDefault()
	{

	}


	public function renderTest()
	{
		Debugger::dump( 'tralala' );

		$this['breadcrumbs']->add('test', ':Admin:Drom:test');

	}



///////component//////////////////////////////////////////////////////

	public function createComponentTestForm()
	{
		$form = new Nette\Application\UI\Form;

		$form->addText('text1', 'Text1')
			->setRequired( 'Pole text 1 je povinne.' )
			->addRule( $form::MIN_LENGTH, 'Pole text 1 musi mat dlzku najmenej %d znakov.', 6);

		$form->addText('text2', 'Text2')
			->setRequired( 'Pole text 2 je povinne.' )
			->addRule( $form::RANGE, 'Pole text 2 musi byt v rozsahu od %d do %d', [3, 6] );

		$form->addSubmit( 'sbmt', 'Submit');


		return $form;
	}



	public function editFormSubmitted( $form )
	{
		return TRUE;
	}


}
